version: '3'
services:
  backend:
    build: ./backend
    hostname: backend
    networks:
      - gif-browsing-app
    ports:
      - "3000:80"
    environment:
      - APP_NAME=Lumen
      - APP_ENV=local
      - APP_KEY=ULQne)-Eg{`Ng^A^N+f^5B#pvVT8d;f&
      - APP_DEBUG=false
      - APP_URL=http://localhost:3000
      - APP_TIMEZONE=UTC
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=gif_browsing_app_db
      - DB_USERNAME=root
      - DB_PASSWORD=mysql_root
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - JWT_EXPIRE_TIME=14400
      - GIPHY_KEY=3QQ8lKxFaw3jZOp3FADOPuqo7sfPjarl
      - GIPHY_URL=https://api.giphy.com/v1
      - GIPHY_GIF_URI=/gifs
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  mysql:
    image: "mysql:5.7.26"
    hostname: mysql
    networks:
      - gif-browsing-app
    environment:
      - MYSQL_ROOT=mysql_root
      - MYSQL_DATABASE=gif_browsing_app_db
    volumes:
      - ~/docker-volumes/mysql-gif-browsing-app:/var/lib/mysql
    ports:
      - "3306:3306"
  frontend:
    build:
      context: ./frontend
      args:
        api_url: http://localhost:3000
    networks:
      - gif-browsing-app
    hostname: frontend
    ports:
      - "80:80"

networks:
  gif-browsing-app: